[package]
name = "rust-programming-introduction"
version = "0.1.0"
authors = ["jarinosuke(Naoki ISHIKAWA) <naokiishikawa0808@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.8"
